name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build tests
        run: g++ -std=c++11 tests/test_encode_decode.cpp -o test
      - name: Run tests
        run: ./test
